# -*- coding: utf-8 -*-
"""Employee Performance Analysys

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Xg3VrkFxfTX24tMutApJeTFHej7P_5X

## **Importing Required Libray And Reading Employee Recoreds Data**
"""

import pandas as pd

df = pd.read_excel("/content/project_2_-_employee_performance_-_final[1].xlsx")

"""## **Inpacting the File**"""

df.head()